### ISSUE TITLE
Picking Emotes Crashes

### ISSUE THREAD

**Issue by isreal6ix** [Shirakumo/Ocelot#1]
***Expected Behavior***

It should allow users to select from the available Emoji's without any error 

***Actual Behavior***

Each time any Emoji is clicked on, the app crashes 

***Test Tools**
* Operating system : Android 6.0
* Phone : Infinix hot s
* Ocelot version 0.1

***How to produce the bug***

Open the App, set up your account (it won't take up to 30sec) 
After opening, click on the text area to input text, select the Emoji icon to bring out all available emoji, now select any Emoji, it'll definitely Crash 

*Recording of the bug is shown below......*

https://youtu.be/fZlKY-Wp4OE

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@beckysophie/bug-in-ocelot-app">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Shinmera** [comment]
Thanks for the report, I'll see what I can do.

**Comment by beckysophie** [comment]
You're welcome

**Comment by Shinmera** [comment]
This should be fixed in 181c27791e828bcf2bbc76d8d16e300631b6f457
