### ISSUE TITLE
Abnormal connection trigger (Rotation)

### ISSUE THREAD

**Issue by organik1** [Shirakumo/Ocelot#3]
Hello dev.
I must add that you've made a nice project here. 

I recent ran into Ocelot and I'm still within the getting familiar phase. I noticed something which I think wasn't intended.
Whenever my display is rotated while viewing Ocelot in offline mode, it suddenly connects on it own.

I use a 6.0 marshmallow android device.

**Comment by Shinmera** [comment]
Thanks for the report, that does indeed sound like a bug.

**Comment by organik1** [comment]
You're welcome. I hope you have a look at the issue soon
